### ISSUE TITLE
Have the regular meeting restarted ?

### ISSUE THREAD

**Issue by EstherLerouzic** [Open-Network-Models-and-Interfaces-ONMI/TAPI-Activities#1]
Would it be possible to participate ?
Thanks!

**Comment by bcjohnso99** [comment]
@EstherLerouzic The weekly TAPI meetings resume on October 29th in the regular timeslot.
https://zoom-lfx.platform.linuxfoundation.org/meetings/onmi-project?view=week

**Comment by EstherLerouzic** [comment]
thanks !
